import React from 'react'
import { ConnectedRouter } from 'react-router-redux'
import { Route } from 'react-router-dom'
import { history } from './../store/configureStore'

import Header from '../containers/Header'
import Home from '../containers/Home'
import Signup from '../containers/Sigup'
import Login from '../containers/Login'
import Favorites from '../containers/Favorites'
